In [1]:
import pandas as pd 
data=pd.read_csv("dataset_countrywise.csv")

In [2]:
data.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-03 22:46:37,34.223334,-82.461707,6,0,0,0,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-03 22:46:37,30.295065,-92.414197,72,1,0,0,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-03 22:46:37,37.767072,-75.632346,8,0,0,0,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-03 22:46:37,43.452658,-116.241552,307,3,0,0,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-03 22:46:37,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US"

In [3]:
country_wise=data.groupby("Country_Region").sum()

In [4]:
country_wise[:10] #so it will group by  country_region all the data

,FIPS,Lat,Long_,Confirmed,Deaths,Recovered,Active
Country_Region,,,,,,,
Afghanistan,0.0,33.93911,67.709953,281,6,10,265
Albania,0.0,41.15330,20.168300,304,17,89,198
Algeria,0.0,28.03390,1.659600,1171,105,62,1004
Andorra,0.0,42.50630,1.521800,439,16,16,407
Angola,0.0,-11.20270,17.873900,8,2,1,5
Antigua and Barbuda,0.0,17.06080,-61.796400,15,0,0,15
Argentina,0.0,-38.41610,-63.616700,1265,39,266,960
Armenia,0.0,40.06910,45.038200,736,7,43,686
Australia,0.0,-256.85020,1130.843900,5330,28,649,4653
Austria,0.0,47.51620,14.550100,11524,168,2022,9334

In [5]:
country_wise["Confirmed"]

Country_Region
Afghanistan            281
Albania                304
Algeria               1171
Andorra                439
Angola                   8
                      ...
Venezuela              153
Vietnam                237
West Bank and Gaza     194
Zambia                  39
Zimbabwe                 9
Name: Confirmed, Length: 181, dtype: int64

In [6]:

folium.Map(location=[28.644800, 77.216721],zoom_start=1)

NameError: name 'folium' is not defined

In [7]:

folium.Map(location=[28.644800, 77.216721],zoom_start=6)

NameError: name 'folium' is not defined

In [8]:

folium.Map(location=[28.644800, 77.216721],zoom_start=10)

NameError: name 'folium' is not defined

In [9]:

folium.Map(location=[28.644800, 77.216721],zoom_start=10,tiles='Stamen Terrain')

NameError: name 'folium' is not defined

In [10]:
#Folium defaults to OpenStreetMap tiles, but Stamen Terrain, Stamen Toner,
# Mapbox Bright, and Mapbox Control room tiles are built in
folium.Map(location=[28.644800, 77.216721],zoom_start=10,tiles='Stamen toner')

NameError: name 'folium' is not defined

In [11]:
data=data.dropna()
#Remove missing values from main data

In [12]:
data[:10]

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-03 22:46:37,34.223334,-82.461707,6,0,0,0,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-03 22:46:37,30.295065,-92.414197,72,1,0,0,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-03 22:46:37,37.767072,-75.632346,8,0,0,0,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-03 22:46:37,43.452658,-116.241552,307,3,0,0,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-03 22:46:37,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US"
5,29001.0,Adair,Missouri,US,2020-04-03 22:46:37,40.190586,-92.600782,6,0,0,0,"Adair, Missouri, US"
6,40001.0,Adair,Oklahoma,US,2020-04-03 22:46:37,35.884942,-94.658593,14,0,0,0,"Adair, Oklahoma, US"
7,8001.0,Adams,Colorado,US,2020-04-03 22:46:37,39.874321,-104.336258,260,7,0,0,"Adams, Colorado, US"
8,16003.0,Adams,Idaho,US,2020-04-03 22:46:37,44.893336,-116.454525,1,0,0,0,"Adams, Idaho, US"
9,17001.0,Adams,Illinois,US,2020-04-03 22:46:37,39.988156,-91.187868,2,0,0,0,"Adams, Illinois, US"

In [13]:
data=data.dropna()

In [50]:
#Folium defaults to OpenStreetMap tiles, but Stamen Terrain, Stamen Toner,
# Mapbox Bright, and Mapbox Control room tiles are built in
folium.Map(location=[28.644800, 77.216721],zoom_start=1,tiles='Stamen toner')

In [51]:
#now we have make circle by seeing confirmed cases from data